"""
XLA HLO Assembly Analyzer for TPU v5e (hlo_analyzer.py)

This script parses High-Level Optimizer (HLO) dumps generated by JAX/XLA.
"""

import os
import glob
import re
import sys
from collections import defaultdict
from typing import Optional

DEFAULT_DUMP_DIR = "/tmp/xla_dump"

PATTERNS = {
    "copy": re.compile(r"=\s*.*copy\("),
    "copy-start": re.compile(r"=\s*.*copy-start\("),
    "copy-done": re.compile(r"=\s*.*copy-done\("),
    "dynamic-slice": re.compile(r"=\s*.*dynamic-slice\("),
}

def find_optimized_hlo_dump(dump_dir: str) -> Optional[str]:
    if not os.path.exists(dump_dir):
        return None

    txt_files = glob.glob(os.path.join(dump_dir, "*.txt"))
    if not txt_files:
        return None

    txt_files.sort(key=os.path.getmtime, reverse=True)

    for file in txt_files:
        if "after_optimizations" in file or "optimized" in file:
            return file
            
    return txt_files[0]

def analyze_hlo_file(filepath: str):
    print(f"\n[HLO Analyzer] Scanning assembly file:\n -> {filepath}")
    
    counts = defaultdict(int)
    total_lines = 0
    
    with open(filepath, 'r') as f:
        for line in f:
            total_lines += 1
            for op_name, pattern in PATTERNS.items():
                if pattern.search(line):
                    counts[op_name] += 1
                    
    return counts, total_lines

def print_diagnostic_report(counts: dict, total_lines: int):
    print("\n============================================================")
    print(" Pallas-Flash: Assembly-Level Diagnostic Report")
    print("============================================================")
    print(f" Total Instructions Analyzed : {total_lines:,}")
    print("------------------------------------------------------------")
    
    # A true "Copy Trap" relies on synchronous copy operations.
    # Async copy-start/done pairs <= 4 are just standard DMA parameter setups.
    sync_copies = counts["copy"]
    async_copies = counts["copy-start"]
    
    print(f" [Instruction Tallies]")
    for op, count in counts.items():
        print(f"   - {op:<20}: {count}")
    print("------------------------------------------------------------")
    
    print(" [Diagnosis]")
    if sync_copies == 0 and async_copies <= 4:
        print(" ✅ SUCCESS: Zero-Copy Kernel Achieved!")
        print("    No implicit padding copies were detected. The layout.py")
        print("    logic successfully aligned all inputs to the v5e MXU.")
        print("    The kernel is strictly compute-bound.")
    elif sync_copies == 0 and async_copies > 4:
        print(" ⚠️  WARNING: High Asynchronous DMA Load")
        print("    No synchronous copies found, but excessive async transfers exist.")
    else:
        print(" ❌ FATAL: THE COPY TRAP TRIGGERED")
        print(f"    {sync_copies} synchronous copy instructions were found!")
        print("    The XLA compiler is manually reshaping tensors because")
        print("    dimensions do not align with the 128x128 systolic array.")
        print("    Action: Check the alignment multiplier in layout.py.")
    
    print("============================================================\n")
    
    if sync_copies > 0:
        return 1
    return 0

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Pallas-Flash HLO Analyzer")
    parser.add_argument("--dir", type=str, default=DEFAULT_DUMP_DIR, 
                        help="Directory containing XLA dumps.")
    args = parser.parse_args()

    hlo_file = find_optimized_hlo_dump(args.dir)
    
    if not hlo_file:
        print(f"[-] No HLO dumps found in {args.dir}.")
        print("[!] Ensure you have run a JAX script with XLA_FLAGS configured.")
        print("    Try running: make debug  -OR-  ./scripts/dump_hlo.sh")
        sys.exit(1)
        
    counts, lines = analyze_hlo_file(hlo_file)
    exit_code = print_diagnostic_report(counts, lines)
    
    sys.exit(exit_code)