"""
XLA HLO Assembly Analyzer for TPU v5e (hlo_analyzer.py)

This script parses High-Level Optimizer (HLO) dumps generated by JAX/XLA.

Context (Phase III - The "Copy Trap"):
The TPU v5e Matrix Multiply Unit (MXU) operates on a strict 128x128 grid.
If a custom Pallas kernel receives tensors that do not cleanly map to these 
dimensions, the XLA compiler silently injects 'copy', 'copy-start', and 
'copy-done' instructions to pad the data in High Bandwidth Memory (HBM) on 
the fly. 

These implicit copies consume massive amounts of the v5e's limited 819 GB/s 
bandwidth. This analyzer scans the optimized HLO graph to ensure that our 
explicit padding in `layout.py` successfully prevented XLA from inserting 
these hidden performance killers.
"""

import os
import glob
import re
import sys
from collections import defaultdict

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

DEFAULT_DUMP_DIR = "/tmp/xla_dump"

# Regex patterns to detect memory-bound XLA operations
# We look for standard copies and asynchronous DMA copy-start/done instructions.
PATTERNS = {
    "copy": re.compile(r"=\s*.*copy\("),
    "copy-start": re.compile(r"=\s*.*copy-start\("),
    "copy-done": re.compile(r"=\s*.*copy-done\("),
    "dynamic-slice": re.compile(r"=\s*.*dynamic-slice\("),
    "dynamic-update-slice": re.compile(r"=\s*.*dynamic-update-slice\("),
}

# -----------------------------------------------------------------------------
# Analysis Logic
# -----------------------------------------------------------------------------

def find_optimized_hlo_dump(dump_dir: str) -> str:
    """
    Locates the final optimized HLO graph from the dump directory.
    XLA dumps many passes; we want the one closest to actual execution.
    """
    if not os.path.exists(dump_dir):
        return None

    txt_files = glob.glob(os.path.join(dump_dir, "*.txt"))
    if not txt_files:
        return None

    # Sort files by modification time (newest first)
    txt_files.sort(key=os.path.getmtime, reverse=True)

    # Prefer the file representing the graph after all optimizations
    for file in txt_files:
        if "after_optimizations" in file or "optimized" in file:
            return file
            
    # Fallback to the most recently modified text file
    return txt_files[0]

def analyze_hlo_file(filepath: str):
    """
    Scans the HLO assembly line-by-line and tallies critical instructions.
    """
    print(f"\n[HLO Analyzer] Scanning assembly file:\n -> {filepath}")
    
    counts = defaultdict(int)
    total_lines = 0
    
    with open(filepath, 'r') as f:
        for line in f:
            total_lines += 1
            for op_name, pattern in PATTERNS.items():
                if pattern.search(line):
                    counts[op_name] += 1
                    
    return counts, total_lines

def print_diagnostic_report(counts: dict, total_lines: int):
    """
    Translates the raw instruction counts into an actionable engineering report.
    """
    print("\n============================================================")
    print(" Pallas-Flash: Assembly-Level Diagnostic Report")
    print("============================================================")
    print(f" Total Instructions Analyzed : {total_lines:,}")
    print("------------------------------------------------------------")
    
    # Check for the dreaded Copy Trap
    total_copies = counts["copy"] + counts["copy-start"]
    
    print(f" [Instruction Tallies]")
    for op, count in counts.items():
        print(f"   - {op:<20}: {count}")
    print("------------------------------------------------------------")
    
    print(" [Diagnosis]")
    if total_copies == 0:
        print(" ✅ SUCCESS: Zero-Copy Kernel Achieved!")
        print("    No implicit padding copies were detected. The layout.py")
        print("    logic successfully aligned all inputs to the v5e MXU.")
        print("    The kernel is strictly compute-bound.")
    elif total_copies < 5:
        print(" ⚠️  WARNING: Minor Copies Detected")
        print("    A small number of copies exist. These may be standard")
        print("    host-to-device transfers, but verify they are not inside")
        print("    the inner 'pipeline_kv_loop'.")
    else:
        print(" ❌ FATAL: THE COPY TRAP TRIGGERED")
        print(f"    {total_copies} copy instructions were found in the graph!")
        print("    The XLA compiler is manually reshaping tensors because")
        print("    dimensions do not align with the 128x128 systolic array.")
        print("    Action: Check the alignment multiplier in layout.py.")
    
    print("============================================================\n")
    
    # Return non-zero exit code if massive copies are found (useful for CI/CD)
    if total_copies > 10:
        return 1
    return 0

# -----------------------------------------------------------------------------
# CLI Entry Point
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Pallas-Flash HLO Analyzer")
    parser.add_argument("--dir", type=str, default=DEFAULT_DUMP_DIR, 
                        help="Directory containing XLA dumps.")
    args = parser.parse_args()

    hlo_file = find_optimized_hlo_dump(args.dir)
    
    if not hlo_file:
        print(f"[-] No HLO dumps found in {args.dir}.")
        print("[!] Ensure you have run a JAX script with XLA_FLAGS configured.")
        print("    Try running: make debug  -OR-  ./scripts/dump_hlo.sh")
        sys.exit(1)
        
    counts, lines = analyze_hlo_file(hlo_file)
    exit_code = print_diagnostic_report(counts, lines)
    
    sys.exit(exit_code)